### ISSUE TITLE
Network location incorrect 

### ISSUE THREAD

**Issue by ADRadu** [patmalcolm91/SumoNetVis#37]
Hello,

I am working on a project and i want to visualize the location of vehicles on the road network via Python. When i plot the location of a vehicle (location retrieved via TraCI) it is not on the road network when plotted with SumoNetVis. I double checked the vehicle location and it is on the roadway when i look at the road network NETEDIT. So the the network location is slight off when visualized with SumoNetEdit. I think the issue may be that it is around a junction. I have attached figures as reference (vehicle location coordinates and SumoNetVis with vehicle location)

Any help would be greatly appreciated.
![DronePointcsv](https://user-images.githubusercontent.com/60677059/178745200-7024fdcd-5397-4877-b434-eefbf2b7e6df.png)
![PointWLines](https://user-images.githubusercontent.com/60677059/178745237-381463c7-64e7-455d-a59e-3ea7442ca30e.png)

**Comment by patmalcolm91** [comment]
Hi @ADRadu. This is very strange behavior, indeed. Does the network have an applied "netOffset" value by chance? If you're able to share the network file, that would help greatly in debugging.

**Comment by patmalcolm91** [comment]
I plotted the coordinates and lane center lines, and everything seems to line up with the SumoNetVis plot (see the orange and blue lines and the blue point on the plot below). I then noticed that you have two x axis scales, each of which is slightly different from the other (see the red vertical line and how the x values on the two axes are different). It seems like you are plotting the network on the bottom axis and the point on the top axis somehow. You should check the code where you set up your secondary axes and where you plot the point from TraCI.
![image](https://user-images.githubusercontent.com/13092577/179368199-ccafafad-6165-431f-ab05-7d6084455f36.png)

**Comment by ADRadu** [comment]
Thank you,

I knew i was plotting the vehicle and road on separate axis but didnt realize the axis werent lined up. I appreciate your help a lot!

**Comment by patmalcolm91** [comment]
No problem! I almost didn't notice the difference since it was so small. Happy to help!
